In [2]:
import numpy as np
import pandas as pd

## Creating Numpy Arrays 

In [3]:
#np.array

a= np.array([1,2,3])
a

array([1, 2, 3])

In [4]:
## 2d array
b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
c = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
c

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [6]:
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [7]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
np.arange(1,11,2) #steps = 2 

array([1, 3, 5, 7, 9])

In [9]:
# reshape
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [10]:
#ones
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
# zeros
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
# random
np.random.random((3,4))

array([[0.13192805, 0.79324942, 0.62992221, 0.28347025],
       [0.46942747, 0.96239933, 0.9418869 , 0.16665986],
       [0.09875907, 0.36233204, 0.32144064, 0.62159555]])

In [13]:
# linspace
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [14]:
# identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
a1 = np.arange(10)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [16]:
a1.ndim

1

In [17]:
a2.ndim

2

In [19]:

a2.shape

(3, 4)

In [22]:
a3.shape
a3 ## there are 2 , 2x2 shape array

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [24]:
# size = no of elements for the array
a3.size

8

In [25]:
a3.itemsize

4